image: archlinux
packages:
- rustup
- xorg-server
- cmake
repositories: {}
shell: false
sources:
  - https://github.com/hackagotchi/tile.git
tasks:
- setup: |
    rustup toolchain install stable
    cd tile/
    rustup run stable cargo fetch
- format: |
    rustup default stable
    cd tile/
    cargo fmt -- --check
- stable: |
    rustup default stable
    cd tile/
    cargo build
    cargo test

